---
title: "Transparency of COVID-19-related research in medical journals"

author:
  - Ahmad Sofi-Mahmudi^[Seqiz Health Network, Kurdistan University of Medical Sciences, Seqiz, Iran.; a.sofimahmudi@gmail.com] ^[Cochrane Iran Associate Centre, National Institute for Medical Research Development (NIMAD), Tehran, Iran.]
  - Eero Raittio*^[Institute of Dentistry, University of Eastern Finland, Kuopio, Finland.; eero.raittio@uef.fi]
  - Sergio E. Uribe^[Department of Conservative Dentistry and Oral Health & Bioinformatics Research Unit, Riga Stradins University, Riga, Latvia.; sergio.uribe@rsu.lv] ^[School of Dentistry, Universidad Austral de Chile, Valdivia, Chile]
  
format:
  docx:
    section-numbers: true
    highlight-style: github 
#format: html
#format:
#  pdf:
#    colorlinks: true
editor: visual
from: markdown+tex_math_single_backslash
bibliography: references.bib
csl: vancouver.csl
---

**Corresponding author:** Eero Raittio; **Address**: University of Eastern Finland, Institute of Dentistry, P.O. Box 1627, FI-70211 Kuopio, Finland; **Telephone**: +358 294 45 1111; **Email**: [eero.raittio\@uef.fi](mailto:eero.raittio@uef.fi).

**Authors' contributions:** All authors conceived and designed, and wrote and revised the protocol.

# What is new

-   key findings

-   what this adds to what is known

-   what is the implication/what should change now

Before completing your submission, please take some time to check that your submission includes "What is new" text, including up to 5 points that address the following areas: key findings, what this adds to what is known, and what is the implication/what should change now.

# Abstract

**Objective:** We aimed to assess the adherence to five transparent practices (data availability, code availability, statements of protocol registration and conflicts of interest and funding disclosures) from open access Coronavirus disease 2019 (COVID-19) related articles.

**Study Design and Setting:** We searched and exported all open access COVID-19-related articles from PubMed-indexed journals available in the Europe PubMed Central database published from January 2020 to the end of February 2022. We detected transparent practices with a validated and automated tool. Basic journal- and article-related information were retrieved from the database. We used R for the analyses.

**Results:** The total number of articles was 175,550, of which we were able to retrieve full texts of 132,598 (76%) articles from the database Of those, 87.0%, (95% CI: 86.8%--87.2%) provided conflicts of interest (COI) disclosure and 68.9% (95% CI: 68.7%--69.2%) funding disclosure and 3.6%, (95% CI: 3.5%--3.7%) had registered protocol. 8.7% (95% CI: 8.6%--8.9%) of studies shared raw data and 3.1% (95% CI: 3.0%--3.2%) of studies shared code. Transparent practices were more common in articles published in 2022. Apart from COI disclosure, articles that adhered to transparency practices were published in journals with slightly higher median Journal Impact Factor but received equal citations.

**Conclusion:** While the majority of the articles were freely available and had a COI disclosure, the adherence to other transparent practices was far from the acceptable level. A much stronger commitment to open science practices, particularly to protocol registration, data and code sharing, is needed from all stakeholders.

***Keywords:*** COVID-19; Data; FAIR data principles; Open Science.

# Introduction

During the recent COVID-19 pandemic, part of the public in developed countries justified their lack of adherence to public health measures due to the lack of transparency of the scientific studies used as an argument by national authorities [@Skipper2020-rs]. Thus, supranational bodies such as the OECD indicate that transparent communication to citizens is vital to support public health measures and to counter misinformation [@Bellantoni_undated-tf]. On the other hand, the COVID-19 pandemic launched an incredibly fast and voluminous avalanche of scientific publications across the different fields of science. This research led to the development of vaccines as well as the evaluation of community interventions. On the one hand, it is possible that transparent scientific practices, like data and code sharing, have helped to fight pandemic globally [@besançon2021; @vuong2022], while on the other hand, the lack of transparency of some key developments has led the public to mistrust the results of research and public health measures [@Skipper2020-rs]. This shows that there is a lack of awareness about the level of transparency practices in COVID-19-related medical literature. As an example, it is unknown whether open science initiatives related to COVID-19 pandemic [@besançon2021; @vuong2022] to advance data sharing, has led to higher number of articles sharing data in COVID-19 research compared to what has been seen in studies in general in biomedical literature [@serghiou2021].

Our aim was to assess the adherence to transparent scientific practices (data sharing, code sharing, conflict of interest, COI, disclosures, funding disclosures, and protocol registration) from open access full-text COVID-19-related articles published in PubMed indexed journals from the Europe PubMed Central (EPMC) database. We mapped adherence to transparent practices across time, journal impact factor (JIF) and citations articles have received

# Methods

The protocol of this study was published beforehand on the Open Science Framework (OSF) website ([osf.io/5kx2n](https://osf.io/5kx2n)). All code and data related to the study were shared via its OSF repository ([osf.io/x3kb6](https://osf.io/x3kb6/)) at the time of submission of the manuscript.

## Data sources and study selection

We searched for open access COVID-19-related PubMed-indexed articles available in the EPMC database. We restricted our search to papers in English and considered papers published from 2020-01-01 to 2021-12-31 with variants of COVID-19 keyword in their title, keywords, or results. This enabled us to bypass screening for COVID-19-related papers and decrease the human labor for our research. We confirmed our approach by choosing a random sample of 500 papers and of those, all but 10 were relevant to COVID-19.

The search query was as follows:

(COVID-19 query for title, keywords, and results) AND (SRC:"MED") AND (LANG:"eng" OR LANG:"en" OR LANG:"us") AND (FIRST_PDATE:[2020-01-01 TO 2021-12-31]) AND (OPEN_ACCESS:y) AND (PUB_TYPE:"Journal Article" OR PUB_TYPE:"research-article" OR PUB_TYPE:"rapid-communication" OR PUB_TYPE:"product-review")'

The full COVID-19 query is available in Appendix 1.

We downloaded all identified available records in XML full-text format (for full-text evaluation) using the metareadr package [@metareadr] from the database.

## Data extraction and synthesis

We assessed articles' adherence to five transparent practices:

-   data sharing,

-   code sharing,

-   COI disclosures,

-   funding disclosures,

-   protocol registration.

To do so, we used a validated and automated tool developed by Serghiou et al. [@serghiou2021] suitable to identify these five transparent practices from articles in XML format from the EPMC database. Regarding data sharing, code sharing and protocol registration the tool identifies whether the article had actually adhered to practice (for instance "data available on request" are not counted as sharing data), whereas COI and funding disclosure merely detect whether articles include the disclosure or not (regardless of its specific content) [@serghiou2021].

Basic journal- and article-related information (publisher, publication year, citations to article and journal name) were retrieved from the EPMC database. We downloaded additional information about journal impact factors from the Journal Citation Reports (ٰ[jcr.clarivate.com](https://jcr.clarivate.com/)).

We also calculated the proportion of articles available as open-access full-texts via the Europe PMC from the total number of COVID-19-related articles in the database.

## Data analysis

We used R v4.1.2 [@base] for searches, data handling, analysis and reporting. The searches and data export from the Europe PMC were conducted with the europepmc package [@europepmc]. Indicators of transparency practices from the available full-texts were extracted with the rtransparent package [@rtransparent]. Trends over time in transparency practices were reported using descriptive tabulations and graphical illustrations using the ggplot2 package [@ggplot2]. We used the sensitivity and specificity of the rtransparent package [@serghiou2021] to generate 95% confidence intervals (CIs) for our prevalence estimates of the transparency practices with the epiR package [@epiR].

Additionally, we calculated how many transparency practices articles had adhered to (from 0 to 5 practices). We used Chi-square for comparing indicators between years and the Wilcoxon rank sum test to test whether there was a relationship between transparency indicators and JIF or received citations. Fisher exact tests with Monte-Carlo simulated p-values for differences in transparency practices by journals and publishers were performed. The thorough information, data and code for the analysis are available as supplementary material on the OSF repository ([osf.io/x3kb6](https://osf.io/x3kb6/)).

# Results

The total number of COVID-19-related articles (open access and non-open access) was 175,544, of which 133,467 (76.0%) were accessible as open-access in the EPMC. However, 869 (0.7%) were not downloadable because of technical issues and thus were excluded from our analyses. Of those 132,598 remaining articles, 47,548 were published in 2020, 75,842 in 2021, and 9,208 in the first two months of 2022.

## Research articles

The majority of articles were research articles (n=103,758; 78.3%). Of these, about 60% were published in 2021 (n=61610). These articles were published in 5,474 journals of which the top five were International Journal of Environmental Research and Public Health (n=3,285), PLoS ONE (n=3,056), Scientific Reports (n=1,711), Frontiers in Psychology (n=1,245), and Frontiers in Public Health (n=1,047). The mean and the median of the number of citations to these articles were 11.8 (standard deviation, SD = 100.31) and 2 (interquartile range, IQR = 7). The highest cited article with 15,549 citations was an article published in The Lancet in 2020 [@huang2020].

About nine-tenth of the articles (n=90,761) had a statement to disclose COI (87.5%, 95% CI: 87.3%--87.7%). Articles published in 2022 had a higher rate of COI disclosure (91.4% (2022), 89.3% (2021), 83.3% (2020), P\<0.001). More than two-thirds of the references had a funding statement (n=74,012) (71.3%, 95% CI: 71.1%--71.6%). Articles in 2022 had a funding statement more frequently than two other years (80.4% (2022), 74.9% (2021), 62.8% (2020), P\<0.001). Less than 1 in 25 of the articles (n=3,934) were registered beforehand (3.8%, 95% CI: 3.7%--3.9%) and the rate was higher in 2022 (5.3% (2022), 4.4% (2021), 2.4% (2020), P\<0.001).

Regarding data and code availability, 10.5% (95% CI: 10.4%--10.7%) of the articles had shared their data (n=11551). Articles in 2022 had shared data more frequently (13.6% (2022), 11.3% (2021), 8.5% (2020), P\<0.001). Similar to registration, 3.8% (95% CI: 3.7%--3.9%) of the articles (n=3,910) had shared their code and the rate was higher in 2022 (4.6% (2022), 4.2% (2021), 2.9 (2020), P\<0.001).

One-twelfth of the articles (8.3%, n=8,562) did not adhere to any of the five transparency practices, 22.0% (n=23,166) adhered to one, 56.0% (n=58,362) adhered to two, and 11.0% (n=11,051) adhered to three. Few (2.5%, n=2,573) articles showed adherence to four transparency practices, and less than 0.1% of the articles (n=44) had used all five practices.

There was a relatively consistent increase in monthly trend for the proportion of articles with COI disclosure and funding disclosure and the proportions were the highest in February 2022 (Figure 1B). Increases in protocol registration, data and code sharing were weaker.

There were journal and publisher-related statistically significant differences in all five practices (p\<0.001 for all). (Table 1 and 2, Supplementary material).

Apart from COI disclosure, articles that adhered to transparency practices were published in journals with slightly higher median JIF but received equal citations (Table 3).

In the validation sample, one of the articles in this sample was just an abstract without any full text. Hence, our validation sample consisted of 49 articles. Of these 49 random articles, nine discrepancies between automatic tool and manual checking were found (3.6%): two for open data, four for COI disclosure, one for funding disclosure, and two for registration (Supplementary material).

## Reviews and other articles

Reviews had a higher proportion of COI disclosure (91.4%, 95% CI: 91.0%--91.8%) compared to research articles but with a lower funding disclosure rate (68.2%, 95% CI: 67.5%--68.9%). Protocol registration was also higher in comparison to research articles (4.4%, 95% CI: 4.1%--4.7%). However, data and code sharing proportions were lower than those of research articles. Other articles had the lowest proportions in all evaluated domains of transparency with zero papers had a registered protocol. Detailed information is available in Supplementary Materials.

Similar to research articles, there was a consistently increasing monthly trend in the proportion of articles with COI and funding disclosures (Figure 1S and 2S).

There were journal and publisher-related statistically significant differences in all five practices (p\<0.001 for all), except for code sharing of review articles (Supplementary Material 3-5).

## Validation

In the validation sample, nine discrepancies between automatic tool and manual checking were found (3.6%): two for open data, four for COI disclosure, one for funding disclosure, and two for registration (Supplementary Material 6).

# Discussion

Adherence to transparent practices increased over time in COVID-19 related medical literature during 2020-2021. Adherence to reporting COI disclosure was high throughout study period, in addition most of articles had funding disclosure. Data sharing, code sharing and protocol registration were rare, but improved little over study period. COI disclosures seemed to be more common in articles published in lower impact journals, otherwise differences in transparent practices according to received citations and JIF were small.

Adherence to transparent practices was at similar level in COVID-19 related literature than in other biomedical literature analyzed with the same methods (see Fig 3 in [@serghiou2021]). This is surprising particularly when considering worldwide, remarkable and noble initiatives related to enhancing open science to tackle the pandemic. As early as in January 2020, over 100 organizations, including journals, publishers, funders, universities and other institutions, signed a statement that aimed to ensure free access to research data, tools and other information related to COVID-19 [@vuong2022; @coronavi]. Later also other initiatives to support the goal emerged, for instance COVID-19 Open Research Dataset (CORD-19)[@cord-19], a free resource of over 280,000 articles about the COVID-19 virus. However, it is possible that the algorithms used here did not efficiently detect all different ways of sharing data and material emerged after the pandemic, because the algorithms were validated before the pandemic [@serghiou2021].

In comparison to other studies on the transparency of COVID-19 related research is difficult due to different methodologies and scale of our research. However, it seems that data sharing was little less common than in our sample than what was the proportion detected in the beginning of the pandemic measured by the investigation of associated data in PubMed Central [@lucas-dominguez2021]. In addition, the proportion of studies which shared data in our study sample was lower than in COVID-19 related preprints shared via medRxiv and bioRxiv [@strcic2022]. Lacking protocol registration, sharing code and COI have got attention during the pandemic [@Glasziou2020a; @besançon2021; @luengo-oroz2020], however we are not aware of the investigation of transparency in these aspects in COVID-19 related research in this scale in medical research.

Despite we used representative data and validated methods to investigate transparency in COVID-19-related research, our study has some weaknesses. The study sample was restricted to open access articles in the EPMC database which may not correspond to all COVID-19-related studies published in medical journals. At least in general, the differences in transparency practices between open access and non-open access articles from Europe PMC are rather similar [@wallach2018a]. However, as the majority of COVID-19-related papers were available via EPMC (76%), this does not diminish the strength of our interpretations considerably.

Transparency is crucial to ensure the credibility of science and enable its assessment. Transparent scientific practices, like the ones we investigated here, have helped to fight pandemic globally [@besançon2021; @vuong2022]. Whilst majority of COVID-19-related articles were open access and had adhered to disclose funding and COI, your findings showed suboptimal adherence to data and code sharing and protocol registration. Stronger commitment to open science practices, particularly to protocol registration, data and code sharing, is needed from all stakeholders.

# Acknowledgements

The computational analyzes were performed on servers provided by UEF Bioinformatics Center, University of Eastern Finland, Finland. The study was supported by a personal grant to ER from the Finnish Dental Society Apollonia.

# References

# Tables

Table 1. Transparency practices in the six most common journals in the sample.

| **Measurement**       | **BMC Oral Health, N = 2503** | **Dental Press J Orthod, N = 530** | **Head Face Med, N = 572** | **J Appl Oral Sci, N = 1440** | **J Indian Prosthodont Soc, N = 495** | **Med Oral Patol Oral Cir Bucal, N = 1174** | **Other, N = 3945** | **p-value** |
|-----------------------|-------------------------------|------------------------------------|----------------------------|-------------------------------|---------------------------------------|---------------------------------------------|---------------------|-------------|
| COI disclosure        | 2489 (99%)                    | 502 (95%)                          | 537 (94%)                  | 303 (21%)                     | 301 (61%)                             | 869 (74%)                                   | 3172 (80%)          | \<0.001     |
| Funding disclosure    | 2232 (89%)                    | 87 (16%)                           | 280 (49%)                  | 656 (46%)                     | 301 (61%)                             | 497 (42%)                                   | 2505 (63%)          | \<0.001     |
| Protocol registration | 326 (13%)                     | 12 (2.3%)                          | 23 (4.0%)                  | 31 (2.2%)                     | 4 (0.8%)                              | 43 (3.7%)                                   | 298 (7.6%)          | \<0.001     |
| Data sharing          | 120 (4.8%)                    | 2 (0.4%)                           | 2 (0.3%)                   | 7 (0.5%)                      | 0 (0%)                                | 5 (0.4%)                                    | 76 (1.9%)           | \<0.001     |
| Code sharing          | 6 (0.2%)                      | 0 (0%)                             | 0 (0%)                     | 0 (0%)                        | 0 (0%)                                | 0 (0%)                                      | 0 (0%)              | 0.61        |

P-values from Fisher's Exact Test for Count Data with simulated p-value (based on 2000 replicates). COI: Conflict of interest.

Table 2. Transparency practices in the six most common publishers of journals in the sample.

| Measurement           | BioMed Central, N = 3075 | Dental Press Editora, N = 530 | Faculdade de Odontologia de Bauru, N = 1440 | Medicina Oral, Patologia Oral y Cirugia Bucal, N 1174 | Springer Verlag, N = 935 | Wolters Kluwer Medknow Publications, N = 495 | Other, N = 2619 | p-value |
|-----------------------|--------------------------|-------------------------------|---------------------------------------------|-------------------------------------------------------|--------------------------|----------------------------------------------|-----------------|---------|
| COI disclosure        | 3026 (98%)               | 502 (95%)                     | 303 (21%)                                   | 869 (74%)                                             | 904 (97%)                | 301 (61%)                                    | 1878 (72%)      | \<0.001 |
| Funding disclosure    | 2512 (82%)               | 87 (16%)                      | 656 (46%)                                   | 497 (42%)                                             | 596 (64%)                | 301 (61%)                                    | 1593 (61%)      | \<0.001 |
| Protocol registration | 349 (11%)                | 12 (2.3%)                     | 31 (2.2%)                                   | 43 (3.7%)                                             | 113 (12%)                | 4 (0.8%)                                     | 144 (5.5%)      | \<0.001 |
| Data sharing          | 122 (4.0%)               | 2 (0.4%)                      | 7 (0.5%)                                    | 5 (0.4%)                                              | 13 (1.4%)                | 0 (0%)                                       | 54 (2.1%)       | \<0.001 |
| Code sharing          | 6 (0.2%)                 | 0 (0%)                        | 0 (0%)                                      | 0 (0%)                                                | 1 (0.1%)                 | 0 (0%)                                       | 1 (\<0.1%)      | 0.68    |

P-values from Fisher's Exact Test for Count Data with simulated p-value (based on 2000 replicates). 391 articles were published in journal without available publisher information. COI: Conflict of interest.

Table 3. Citations to article and journal impact factor by transparency practices.

|                    | Citations to article |         |          | Journal Impact Factor |            |          |
|--------------------|----------------------|---------|----------|:----------------------|:-----------|----------|
| Measurement        | Median (IQR)         |         | P-Value  | Median (IQR)          |            | P-value  |
|                    | With                 | Without |          | With                  | Without    |          |
| COI disclosure     | 2 (5)                | 5 (9)   | \< 0.001 | 2.8 (0.61)            | 2.7 (0.06) | \< 0.001 |
| Funding disclosure | 2 (5)                | 3 (7)   | \< 0.001 | 2.8 (0.06)            | 2.7 (0.70) | \< 0.001 |
| Registration       | 1 (4)                | 2 (7)   | \< 0.001 | 2.8 (0.01)            | 2.7 (0.61) | \< 0.001 |
| Data sharing       | 2 (4)                | 2 (7)   | 0.01     | 2.8 (0.00)            | 2.8 (0.49) | \< 0.001 |
| Code sharing       | 1.5 (3)              | 2 (7)   | 0.70     | 2.8 (0.00)            | 2.8 (0.49) | 0.08     |

P-value based on the Wilcoxon rank sum test. 1929 articles were published in journals with no impact factor. COI: Conflict of interest; SD: Standard deviation; IQR: Inter-quartile range.
